version: '3.9'

services:
    
  broker:
    container_name: mqtt
    build:
      context: ./mqtt/
    ports:
      - '1883:1883'
    volumes:
      - './mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf'
    restart: always
